#!/bin/sh -e
export PATH="/data/sbin:/data/bin:/opt/gomicro/sbin:/opt/gomicro/bin:/opt/local/sbin:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

exec chpst -u gomicro /data/bin/postgres -D /data/var/db/postgresql 2>&1
